"""
Django settings for BrakePoint_Project project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import sys

BASE_DIR = Path(__file__).resolve().parent.parent

_tmp_dir = str(BASE_DIR / 'tmp')
os.makedirs(_tmp_dir, exist_ok=True)
os.environ.setdefault('TMPDIR', _tmp_dir)
os.environ.setdefault('TEMP', _tmp_dir)
os.environ.setdefault('TMP', _tmp_dir)

load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-fallback-key")

DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "103.231.240.148",
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "BrakePoint",
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://103.231.240.148:32010",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://103.231.240.148:32010",
]

SESSION_COOKIE_SAMESITE = None 
SESSION_COOKIE_SECURE = False  
SESSION_COOKIE_HTTPONLY = False 
SESSION_COOKIE_DOMAIN = None  

CSRF_COOKIE_SAMESITE = None
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False  

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

ROOT_URLCONF = "BrakePoint_Project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "BrakePoint_Project.wsgi.application"

# Determine SSL cert path based on OS
_ca_cert_path = os.path.join(BASE_DIR, 'certs', 'isrg-root-x1.pem')

if sys.platform == 'darwin':
    _mac_cert_candidates = [
        '/etc/ssl/cert.pem',
        '/opt/homebrew/etc/openssl@3/cert.pem',
        '/opt/homebrew/etc/openssl/cert.pem',
        '/usr/local/etc/openssl@3/cert.pem',
        '/usr/local/etc/openssl/cert.pem',
    ]
    _ca_cert_path = None
    for _candidate in _mac_cert_candidates:
        if os.path.exists(_candidate):
            _ca_cert_path = _candidate
            break
    if _ca_cert_path is None:
        try:
            import certifi
            _ca_cert_path = certifi.where()
        except ImportError:
            _ca_cert_path = None
elif sys.platform == 'win32':
    if not os.path.exists(_ca_cert_path):
        try:
            import certifi
            _ca_cert_path = certifi.where()
        except ImportError:
            _ca_cert_path = None
else:
    # Linux — use system CA bundle
    _linux_cert_candidates = [
        '/etc/ssl/certs/ca-certificates.crt',
        '/etc/pki/tls/certs/ca-bundle.crt',
        '/etc/ssl/ca-bundle.pem',
    ]
    if not os.path.exists(_ca_cert_path):
        _ca_cert_path = None
        for _candidate in _linux_cert_candidates:
            if os.path.exists(_candidate):
                _ca_cert_path = _candidate
                break
    if _ca_cert_path is None:
        try:
            import certifi
            _ca_cert_path = certifi.where()
        except ImportError:
            _ca_cert_path = None

if _ca_cert_path and os.path.exists(_ca_cert_path):
    _ssl_options = {'ssl': {'ca': _ca_cert_path}}
else:
    _ssl_options = {'ssl': True}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# SQLite (local development fallback)
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# TiDB Cloud Serverless (shared database)
DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.mysql"),
        "NAME": os.getenv("DB_NAME", "defaultdb"),
        "USER": os.getenv("DB_USER", ""),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "4000"),
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            **_ssl_options,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DATA_UPLOAD_MAX_MEMORY_SIZE = None  # no limit
FILE_UPLOAD_MAX_MEMORY_SIZE = 0     # always stream to disk

FILE_UPLOAD_TEMP_DIR = str(BASE_DIR / 'tmp')
